### ISSUE TITLE
AssertionError during sacad_r

### ISSUE THREAD

**Issue by mn113** [desbma/sacad#24]
The sacad_r script broke while downloading covers for me. The output is below, maybe it can help in pinpointing & catching the error.

```
[martin@MBP2018  sacad (git:master ✗)]$ sacad_r ~/allmp3s 500 cover.jpg
Analyzing library: 2586 dirs [01:39, 26.10 dirs/s, files=38199, albums=2569, missing covers=2467, errors=2]
Searching covers:   7%|████▊                                                                 | 171/2465 [04:55<48:05,  1.26s/ covers, ok=164, errors=1, no result found=6]
Traceback (most recent call last):
  File "/usr/local/bin/sacad_r", line 11, in <module>
    load_entry_point('sacad==2.1.8', 'console_scripts', 'sacad_r')()
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/recurse.py", line 317, in cl_main
    get_covers(work, args)
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/recurse.py", line 267, in get_covers
    async_loop.run_until_complete(root_future)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/recurse.py", line 210, in update_progress
    status = future.result()
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/__init__.py", line 46, in search_and_download
    source_results = future.result()
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/sources/base.py", line 92, in search
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/cover.py", line 306, in updateImageMetadata
    self.setSizeMetadata((width_sum, height_sum))
  File "/usr/local/lib/python3.7/site-packages/sacad-2.1.8-py3.7.egg/sacad/cover.py", line 322, in setSizeMetadata
    (self.size == size))
AssertionError
```

**Comment by desbma** [comment]
This is similar to #20, and should already be fixed if you update to version 2.1.9.
