### ISSUE TITLE
sacad_r fails with assertion error while scanning music library

### ISSUE THREAD

**Issue by dshanks01** [desbma/sacad#25]
Ran sacad_r version 2.1.9 as
```
$ sacad_r -t 50 -d . 1000 AlbumArt.jpg
```

Got to 20% complete and failed:
```
Traceback (most recent call last):
  File "/home/david/.local/bin/sacad_r", line 11, in <module>
    sys.exit(cl_main())
  File "/home/david/.local/lib/python3.6/site-packages/sacad/recurse.py", line 315, in cl_main
    get_covers(work, args)
  File "/home/david/.local/lib/python3.6/site-packages/sacad/recurse.py", line 265, in get_covers
    async_loop.run_until_complete(root_future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/david/.local/lib/python3.6/site-packages/sacad/recurse.py", line 208, in update_progress
    status = future.result()
  File "/home/david/.local/lib/python3.6/site-packages/sacad/__init__.py", line 46, in search_and_download
    source_results = future.result()
  File "/home/david/.local/lib/python3.6/site-packages/sacad/sources/base.py", line 94, in search
    future.result()  # raise pending exception if any
  File "/home/david/.local/lib/python3.6/site-packages/sacad/cover.py", line 246, in updateImageMetadata
    self.setFormatMetadata(format)
  File "/home/david/.local/lib/python3.6/site-packages/sacad/cover.py", line 316, in setFormatMetadata
    (self.format is format))
AssertionError
```

**Comment by desbma** [comment]
Thanks for the report, it should be fixed now.
