### ISSUE TITLE
sacad_r: OSError: [Errno 24] Too many open files: '/home/<USER>/.cache/sacad/fake_useragent/ua.json'

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#33]
```
Analyzing library: 1889dir [00:38, 49.57dir/s, files=21532, albums=1496, missing covers=1053, errors=0]
Searching covers:  14%|███████████████▎                                                                                                | 144/1053 [06:58<43:58,  2.90s/cover, ok=60, errors=16, no result found=68]
Traceback (most recent call last):
  File "/home/<USER>/.local/bin//sacad_r", line 10, in <module>
    sys.exit(cl_main())
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/recurse.py", line 429, in cl_main
    get_covers(work, args)
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/recurse.py", line 357, in get_covers
    asyncio.get_event_loop().run_until_complete(root_future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/recurse.py", line 293, in post_download
    status = future.result()
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/__init__.py", line 24, in search_and_download
    cover_sources = [sources.LastFmCoverSource(*source_args),
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/sources/lastfm.py", line 34, in __init__
    super().__init__(*args, min_delay_between_accesses=0.1, **kwargs)
  File "/home/<USER>/.local/lib/python3.7/site-packages/sacad/sources/base.py", line 43, in __init__
    self.ua = fake_useragent.UserAgent(path=os.path.join(ua_cache_dir, "ua.json"))
  File "/home/<USER>/.local/lib/python3.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/home/<USER>/.local/lib/python3.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/home/<USER>/.local/lib/python3.7/site-packages/fake_useragent/utils.py", line 252, in load_cached
    return read(path)
  File "/home/<USER>/.local/lib/python3.7/site-packages/fake_useragent/utils.py", line 229, in read
    with io.open(path, encoding='utf-8', mode='rt') as fp:
OSError: [Errno 24] Too many open files: '/home/<USER>/.cache/sacad/fake_useragent/ua.json'
```
Maybe implementing https://github.com/desbma/sacad/issues/32 would help with this too.

**Comment by desbma** [comment]
Can you please privide:
* Sacad version and how you have installed it
* Python version (`Python -V`)
* Output of `ulimit -n`

**Comment by maszaa** [comment]
- Python 3.7.3
- sacad 2.2.3, installled inside venv, venv created with venv module usign python 3.7.3
- ulimit -n: 1024

I guess the ulimit value is the problem. Maybe sacad_r should respect it.

**Comment by desbma** [comment]
Can you try git master branch (ie with `pip install git+https://github.com/desbma/sacad`) ?

**Comment by maszaa** [comment]
Seems to be working better now
