### ISSUE TITLE
ValueError on Win64 standalone binary

### ISSUE THREAD

**Issue by grumblegoose** [desbma/sacad#45]
When running "sacad_r path 600 Cover.jpg" (where "path" is the music library filepath), a ValueError is always thrown after about 20-40 cover searches. "ValueError: too many file descriptors in select()"

[Screen capture of traceback](https://i.imgur.com/5gMguxs.png)

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "sacad\recurse.py", line 451, in <module>
  File "sacad\recurse.py", line 447, in cl_main
  File "sacad\recurse.py", line 362, in get_covers
  File "C:\Python36\lib\asyncio\base_events.py", line 471, in run_until_complete
  File "C:\Python36\lib\asyncio\base_events.py", line 438, in run_forever
  File "C:\Python36\lib\asyncio\base_events.py", line 1415, in _run_once
  File "C:\Python36\lib\selectors.py", line 323, in select
  File "C:\Python36\lib\selectors.py", line 314, in _select
ValueError: too many file descriptors in select()

version 2.3.2 standalone binary on Windows 10 x64 machine

**Comment by desbma** [comment]
It should be fixed by https://github.com/desbma/sacad/commit/ff174321cf1490ba5b60125b72fd51cca9081f7e in the next version.
