### ISSUE TITLE
AttributeError: module 'bitarray' has no attribute 'bitdiff'

### ISSUE THREAD

**Issue by Ranthalion** [desbma/sacad#48]
A fresh install of python3, pip3, and sacad results in the following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/sacad_r", line 10, in <module>
    sys.exit(cl_main())
  File "/usr/local/lib/python3.7/dist-packages/sacad/recurse.py", line 448, in cl_main
    get_covers(work, args)
  File "/usr/local/lib/python3.7/dist-packages/sacad/recurse.py", line 363, in get_covers
    asyncio.get_event_loop().run_until_complete(root_future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/sacad/recurse.py", line 298, in post_download
    status = future.result()
  File "/usr/local/lib/python3.7/dist-packages/sacad/__init__.py", line 51, in search_and_download
    results = await CoverSourceResult.preProcessForComparison(results, size, size_tolerance_prct)
  File "/usr/local/lib/python3.7/dist-packages/sacad/cover.py", line 624, in preProcessForComparison
    reference.thumbnail_sig)
  File "/usr/local/lib/python3.7/dist-packages/sacad/cover.py", line 667, in areImageSigsSimilar
    return bitarray.bitdiff(sig1, sig2) < 100
AttributeError: module 'bitarray' has no attribute 'bitdiff'
```

bitdiff was deprecated in 1.6.0 and should be replaced with bitarray.util.count_xor() based on https://github.com/ilanschnell/bitarray#change-log.

**Comment by desbma** [comment]
Thanks
