### ISSUE TITLE
errormessage afterupdating from 2.4 to 2.5

### ISSUE THREAD

**Issue by morbificagent** [desbma/sacad#68]
After the update it doesnt work anymore:

sacad_r: Error occured while searching cover for xxx.mp3': TypeError not all arguments converted during string formatting

Traceback (most recent call last):
  File "/usr/bin/sacad_r", line 33, in <module>
    sys.exit(load_entry_point('sacad==2.5.0', 'console_scripts', 'sacad_r')())
  File "/usr/local/lib/python3.8/dist-packages/sacad/recurse.py", line 458, in cl_main
    get_covers(work, args)
  File "/usr/local/lib/python3.8/dist-packages/sacad/recurse.py", line 367, in get_covers
    asyncio.get_event_loop().run_until_complete(root_future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/sacad/recurse.py", line 300, in post_download
    status = future.result()
  File "/usr/local/lib/python3.8/dist-packages/sacad/__init__.py", line 65, in search_and_download
    source_results = future.result()
  File "/usr/local/lib/python3.8/dist-packages/sacad/sources/base.py", line 122, in search
    future.result()  # raise pending exception if any
  File "/usr/local/lib/python3.8/dist-packages/sacad/cover.py", line 325, in updateImageMetadata
    f"Unable to get file metadata from file or HTTP headers for URL {url!r}, "
TypeError: not all arguments converted during string formatting

Any idea what to do?

**Comment by morbificagent** [comment]
ok, i should have updated my ubuntu...

sorry
