### ISSUE TITLE
sacad 2.6 (win32 exe) and discogs

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#74]
i just tested sacad 2.6 (win32 exe) with the following command:

sacad.exe -t 100 "BOLCHI" "HANDLE LOVE" 320 "BOLCHI - HANDLE LOVE.jpg"

the console show the following log:

Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
AmazonDigitalCoverSource: Got 16 relevant (0 excluded) results from source 'AmazonDigitalCoverSource'
DeezerCoverSource: Got 0 relevant (0 excluded) results from source 'DeezerCoverSource'
GoogleImagesWebScrapeCoverSource: Got 0 relevant (0 excluded) results from source 'GoogleImagesWebScrapeCoverSource'
DiscogsCoverSource: Got 0 relevant (0 excluded) results from source 'DiscogsCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
LastFmCoverSource: Search with source 'LastFmCoverSource' failed: ClientResponseError 404, message='Not Found', url=URL('https://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=2410a53db5c7490d0f50c100a020f359&album=handle+love&artist=bolchi')
Cover: No reference result found
Cover: Downloading cover 'https://m.media-amazon.com/images/I/81yl-C+81sL.jpg' (part 1/1)...
Cover: Resizing from 2560x2560 to 320x320...
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03AA4F58>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03AA4F58>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03AA4F58>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03AA4F58>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03AA4F58>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

and i get again this wrong cover
![BOLCHI - HANDLE LOVE](https://user-images.githubusercontent.com/99482352/184954050-df59bace-ab15-4b63-8066-6564b5eca60e.jpg)

instead of the right cover from discogs:

https://www.discogs.com/it/release/2609772-Bolchi-City-Trippin

**Comment by desbma** [comment]
As I already told you in https://github.com/desbma/sacad/issues/72#issuecomment-1214364286 you are searching for "Handle Love", which is a track name, Sacad is design to search by artist and album.

`sacad Bolchi 'City Trippin' 600 /tmp/a.jpg -t 75` gives the correct cover from Discogs for example, although it is very low quality.
