### ISSUE TITLE
sacad v 2.7.1 installation failed

### ISSUE THREAD

**Issue by chicco64** [desbma/sacad#82]
Hi !
after a long time I did a new installation of your software, but I get errors in its execution:

------------------------------------------------------------------------------
apt-get install build-essential python3-dev python3-pip -y
python3 -m pip install --upgrade pip setuptools wheel   
python3 -m pip install sacad
apt-get install optipng jpegoptim -y

sacad -h
SACAD v2.7.1. Search and download an album cover

sacad -p -v 'normal' "michael jackson" "thriller" 600 cover.jpg

Traceback (most recent call last):
  File "/usr/bin/sacad", line 33, in <module>
    sys.exit(load_entry_point('sacad==2.7.1', 'console_scripts', 'sacad')())
  File "/usr/local/lib/python3.9/dist-packages/sacad/__init__.py", line 221, in cl_main
    asyncio.run(coroutine)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/sacad/__init__.py", line 47, in search_and_download
    cover_sources = [cls(*source_args) for cls in source_classes]
  File "/usr/local/lib/python3.9/dist-packages/sacad/__init__.py", line 47, in <listcomp>
    cover_sources = [cls(*source_args) for cls in source_classes]
  File "/usr/local/lib/python3.9/dist-packages/sacad/sources/amazoncd.py", line 39, in __init__
    super().__init__(*args, base_domain=urllib.parse.urlsplit(self.base_url).netloc, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sacad/sources/amazonbase.py", line 11, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/sacad/sources/base.py", line 52, in __init__
    self.ua = fake_useragent.UserAgent(
TypeError: __init__() got an unexpected keyword argument 'path'

-----------------------------------------------------------------------------------------

The older version (SACAD v2.5.0.) works fine....

Can you help me ?

Many thanks !

**Comment by ianbattersby** [comment]
@chicco64 I had the same issue, had to pin `fake-useragent==0.1.14` 👍

**Comment by desbma** [comment]
I will remove the `fake-useragent` dependency altogether, the developer either has no idea of what he is doing or simply does not care, he has already broken the API compatibility several times in recent releases, and continues to do so in [last commits](https://github.com/fake-useragent/fake-useragent/commit/8013f98f970f3f691f392bb1ed73e0b5ae67595b).

**Comment by desbma** [comment]
Fixed in 10365f2.
